### ISSUE TITLE
Add the ability to add packages

### ISSUE THREAD

**Issue by LindseyB** [LindseyB/trackify#1]
- Should be able to recognize from tracking which of the types below it is
- Should be able to change the carrier of the package

```[tasklist]
### Tasks
- [ ] Add a USPS package
- [ ] Add a amazon package from a tracking link
- [ ] Add a fedex package
- [ ] Add a UPS package
- [ ] Add a LaserShip/OnTrac package
- [ ] Add a placeholder package 
```
